package com.example.quizapp2

import androidx.lifecycle.ViewModel

class GameModel : ViewModel() {
    private val question = listOf<Question>(
        Question("Art",R.string.question_text_A1, R.string.Canswer_text_A1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Art",R.string.question_text_A2, R.string.Canswer_text_A2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Art",R.string.question_text_A3, R.string.Canswer_text_A3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Art",R.string.question_text_A4, R.string.Canswer_text_A4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Art",R.string.question_text_A5, R.string.Canswer_text_A5,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Geography",R.string.question_text_G1, R.string.Canswer_text_G1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Geography",R.string.question_text_G2, R.string.Canswer_text_G2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Geography",R.string.question_text_G3, R.string.Canswer_text_G3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Geography",R.string.question_text_G4, R.string.Canswer_text_G4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Geography",R.string.question_text_G5, R.string.Canswer_text_G5,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("History",R.string.question_text_H1, R.string.Canswer_text_H1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("History",R.string.question_text_H2, R.string.Canswer_text_H2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("History",R.string.question_text_H3, R.string.Canswer_text_H3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("History",R.string.question_text_H4, R.string.Canswer_text_H4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("History",R.string.question_text_H5, R.string.Canswer_text_H5,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Movies",R.string.question_text_M1, R.string.Canswer_text_M1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Movies",R.string.question_text_M2, R.string.Canswer_text_M2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Movies",R.string.question_text_M3, R.string.Canswer_text_M3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Movies",R.string.question_text_M4, R.string.Canswer_text_M4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Movies",R.string.question_text_M5, R.string.Canswer_text_M5,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Literature",R.string.question_text_L1, R.string.Canswer_text_L1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Literature",R.string.question_text_L2, R.string.Canswer_text_L2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Literature",R.string.question_text_L3, R.string.Canswer_text_L3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Literature",R.string.question_text_L4, R.string.Canswer_text_L4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Literature",R.string.question_text_L5, R.string.Canswer_text_L5,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Science",R.string.question_text_S1, R.string.Canswer_text_S1,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Science",R.string.question_text_S2, R.string.Canswer_text_S2,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Science",R.string.question_text_S3, R.string.Canswer_text_S3,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Science",R.string.question_text_S4, R.string.Canswer_text_S4,"#000000", listOf<Int>(0), listOf<Int>()),
        Question("Science",R.string.question_text_S5, R.string.Canswer_text_S5,"#000000", listOf<Int>(0), listOf<Int>())
    )
    private var ans = listOf<Answer>(
        Answer(R.string.question_text_A1, R.string.I1answer_text_A1),
        Answer(R.string.question_text_A1, R.string.I2answer_text_A1),
        Answer(R.string.question_text_A1, R.string.I3answer_text_A1),
        Answer(R.string.question_text_A2, R.string.I1answer_text_A2),
        Answer(R.string.question_text_A2, R.string.I2answer_text_A2),
        Answer(R.string.question_text_A2, R.string.I3answer_text_A2),
        Answer(R.string.question_text_A3, R.string.I1answer_text_A3),
        Answer(R.string.question_text_A3, R.string.I2answer_text_A3),
        Answer(R.string.question_text_A3, R.string.I3answer_text_A3),
        Answer(R.string.question_text_A4, R.string.I3answer_text_A4),
        Answer(R.string.question_text_A4, R.string.I1answer_text_A4),
        Answer(R.string.question_text_A4, R.string.I2answer_text_A4),
        Answer(R.string.question_text_A5, R.string.I3answer_text_A5),
        Answer(R.string.question_text_A5, R.string.I1answer_text_A5),
        Answer(R.string.question_text_A5, R.string.I2answer_text_A5),
        Answer(R.string.question_text_G1, R.string.I1answer_text_G1),
        Answer(R.string.question_text_G1, R.string.I2answer_text_G1),
        Answer(R.string.question_text_G1, R.string.I3answer_text_G1),
        Answer(R.string.question_text_G2, R.string.I1answer_text_G2),
        Answer(R.string.question_text_G2, R.string.I2answer_text_G2),
        Answer(R.string.question_text_G2, R.string.I3answer_text_G2),
        Answer(R.string.question_text_G3, R.string.I1answer_text_G3),
        Answer(R.string.question_text_G3, R.string.I2answer_text_G3),
        Answer(R.string.question_text_G3, R.string.I3answer_text_G3),
        Answer(R.string.question_text_G4, R.string.I3answer_text_G4),
        Answer(R.string.question_text_G4, R.string.I1answer_text_G4),
        Answer(R.string.question_text_G4, R.string.I2answer_text_G4),
        Answer(R.string.question_text_G5, R.string.I3answer_text_G5),
        Answer(R.string.question_text_G5, R.string.I1answer_text_G5),
        Answer(R.string.question_text_G5, R.string.I2answer_text_G5),
        Answer(R.string.question_text_H1, R.string.I1answer_text_H1),
        Answer(R.string.question_text_H1, R.string.I2answer_text_H1),
        Answer(R.string.question_text_H1, R.string.I3answer_text_H1),
        Answer(R.string.question_text_H2, R.string.I1answer_text_H2),
        Answer(R.string.question_text_H2, R.string.I2answer_text_H2),
        Answer(R.string.question_text_H2, R.string.I3answer_text_H2),
        Answer(R.string.question_text_H3, R.string.I1answer_text_H3),
        Answer(R.string.question_text_H3, R.string.I2answer_text_H3),
        Answer(R.string.question_text_H3, R.string.I3answer_text_H3),
        Answer(R.string.question_text_H4, R.string.I3answer_text_H4),
        Answer(R.string.question_text_H4, R.string.I1answer_text_H4),
        Answer(R.string.question_text_H4, R.string.I2answer_text_H4),
        Answer(R.string.question_text_H5, R.string.I3answer_text_H5),
        Answer(R.string.question_text_H5, R.string.I1answer_text_H5),
        Answer(R.string.question_text_H5, R.string.I2answer_text_H5),
        Answer(R.string.question_text_M1, R.string.I1answer_text_M1),
        Answer(R.string.question_text_M1, R.string.I2answer_text_M1),
        Answer(R.string.question_text_M1, R.string.I3answer_text_M1),
        Answer(R.string.question_text_M2, R.string.I1answer_text_M2),
        Answer(R.string.question_text_M2, R.string.I2answer_text_M2),
        Answer(R.string.question_text_M2, R.string.I3answer_text_M2),
        Answer(R.string.question_text_M3, R.string.I1answer_text_M3),
        Answer(R.string.question_text_M3, R.string.I2answer_text_M3),
        Answer(R.string.question_text_M3, R.string.I3answer_text_M3),
        Answer(R.string.question_text_M4, R.string.I3answer_text_M4),
        Answer(R.string.question_text_M4, R.string.I1answer_text_M4),
        Answer(R.string.question_text_M4, R.string.I2answer_text_M4),
        Answer(R.string.question_text_M5, R.string.I3answer_text_M5),
        Answer(R.string.question_text_M5, R.string.I1answer_text_M5),
        Answer(R.string.question_text_M5, R.string.I2answer_text_M5),
        Answer(R.string.question_text_L1, R.string.I1answer_text_L1),
        Answer(R.string.question_text_L1, R.string.I2answer_text_L1),
        Answer(R.string.question_text_L1, R.string.I3answer_text_L1),
        Answer(R.string.question_text_L2, R.string.I1answer_text_L2),
        Answer(R.string.question_text_L2, R.string.I2answer_text_L2),
        Answer(R.string.question_text_L2, R.string.I3answer_text_L2),
        Answer(R.string.question_text_L3, R.string.I1answer_text_L3),
        Answer(R.string.question_text_L3, R.string.I2answer_text_L3),
        Answer(R.string.question_text_L3, R.string.I3answer_text_L3),
        Answer(R.string.question_text_L4, R.string.I3answer_text_L4),
        Answer(R.string.question_text_L4, R.string.I1answer_text_L4),
        Answer(R.string.question_text_L4, R.string.I2answer_text_L4),
        Answer(R.string.question_text_L5, R.string.I3answer_text_L5),
        Answer(R.string.question_text_L5, R.string.I1answer_text_L5),
        Answer(R.string.question_text_L5, R.string.I2answer_text_L5),
        Answer(R.string.question_text_S1, R.string.I1answer_text_S1),
        Answer(R.string.question_text_S1, R.string.I2answer_text_S1),
        Answer(R.string.question_text_S1, R.string.I3answer_text_S1),
        Answer(R.string.question_text_S2, R.string.I1answer_text_S2),
        Answer(R.string.question_text_S2, R.string.I2answer_text_S2),
        Answer(R.string.question_text_S2, R.string.I3answer_text_S2),
        Answer(R.string.question_text_S3, R.string.I1answer_text_S3),
        Answer(R.string.question_text_S3, R.string.I2answer_text_S3),
        Answer(R.string.question_text_S3, R.string.I3answer_text_S3),
        Answer(R.string.question_text_S4, R.string.I3answer_text_S4),
        Answer(R.string.question_text_S4, R.string.I1answer_text_S4),
        Answer(R.string.question_text_S4, R.string.I2answer_text_S4),
        Answer(R.string.question_text_S5, R.string.I3answer_text_S5),
        Answer(R.string.question_text_S5, R.string.I1answer_text_S5),
        Answer(R.string.question_text_S5, R.string.I2answer_text_S5)
    )

}